// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "jadwaldokter/features/dokter/domain"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Add provides a mock function with given fields: newItem
func (_m *Repository) Add(newItem domain.DokterCore) (domain.DokterCore, error) {
	ret := _m.Called(newItem)

	var r0 domain.DokterCore
	if rf, ok := ret.Get(0).(func(domain.DokterCore) domain.DokterCore); ok {
		r0 = rf(newItem)
	} else {
		r0 = ret.Get(0).(domain.DokterCore)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.DokterCore) error); ok {
		r1 = rf(newItem)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ID
func (_m *Repository) Delete(ID uint) (domain.DokterCore, error) {
	ret := _m.Called(ID)

	var r0 domain.DokterCore
	if rf, ok := ret.Get(0).(func(uint) domain.DokterCore); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Get(0).(domain.DokterCore)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields:
func (_m *Repository) GetAll() ([]domain.DokterCore, error) {
	ret := _m.Called()

	var r0 []domain.DokterCore
	if rf, ok := ret.Get(0).(func() []domain.DokterCore); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DokterCore)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
