// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "jadwaldokter/features/jadwal/domain"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Add provides a mock function with given fields: newJadwal
func (_m *Repository) Add(newJadwal domain.JadwalCore) (domain.JadwalCore, error) {
	ret := _m.Called(newJadwal)

	var r0 domain.JadwalCore
	if rf, ok := ret.Get(0).(func(domain.JadwalCore) domain.JadwalCore); ok {
		r0 = rf(newJadwal)
	} else {
		r0 = ret.Get(0).(domain.JadwalCore)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.JadwalCore) error); ok {
		r1 = rf(newJadwal)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *Repository) Delete(id uint) (domain.JadwalCore, error) {
	ret := _m.Called(id)

	var r0 domain.JadwalCore
	if rf, ok := ret.Get(0).(func(uint) domain.JadwalCore); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.JadwalCore)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: hari
func (_m *Repository) GetAll(hari string) ([]domain.JadwalCore, error) {
	ret := _m.Called(hari)

	var r0 []domain.JadwalCore
	if rf, ok := ret.Get(0).(func(string) []domain.JadwalCore); ok {
		r0 = rf(hari)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.JadwalCore)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(hari)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
