// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "jadwaldokter/features/poli/domain"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Add provides a mock function with given fields: newPoli
func (_m *Repository) Add(newPoli domain.PoliCore) (domain.PoliCore, error) {
	ret := _m.Called(newPoli)

	var r0 domain.PoliCore
	if rf, ok := ret.Get(0).(func(domain.PoliCore) domain.PoliCore); ok {
		r0 = rf(newPoli)
	} else {
		r0 = ret.Get(0).(domain.PoliCore)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.PoliCore) error); ok {
		r1 = rf(newPoli)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *Repository) Delete(id uint) (domain.PoliCore, error) {
	ret := _m.Called(id)

	var r0 domain.PoliCore
	if rf, ok := ret.Get(0).(func(uint) domain.PoliCore); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.PoliCore)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields:
func (_m *Repository) GetAll() ([]domain.PoliCore, error) {
	ret := _m.Called()

	var r0 []domain.PoliCore
	if rf, ok := ret.Get(0).(func() []domain.PoliCore); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PoliCore)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: upPoli, poliID
func (_m *Repository) Update(upPoli domain.PoliCore, poliID uint) (domain.PoliCore, error) {
	ret := _m.Called(upPoli, poliID)

	var r0 domain.PoliCore
	if rf, ok := ret.Get(0).(func(domain.PoliCore, uint) domain.PoliCore); ok {
		r0 = rf(upPoli, poliID)
	} else {
		r0 = ret.Get(0).(domain.PoliCore)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.PoliCore, uint) error); ok {
		r1 = rf(upPoli, poliID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
